/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    InputBar: typeof import('./components/chat/InputBar.vue')['default']
    IntentTagBar: typeof import('./components/chat/IntentTagBar.vue')['default']
    KnowledgeSourceCollapse: typeof import('./components/chat/KnowledgeSourceCollapse.vue')['default']
    MessageBubble: typeof import('./components/chat/MessageBubble.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanBadge: typeof import('vant/es')['Badge']
    VanEmpty: typeof import('vant/es')['Empty']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanNoticeBar: typeof import('vant/es')['NoticeBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanTag: typeof import('vant/es')['Tag']
  }
}
